B_drive/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('drive.urls', namespace="drive"))
]

drive/urls.py
from django.urls import path

from .views import Login, Upload, logout, show_my_files, show_subs_files


app_name = 'drive'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('my-files/', show_my_files, name="show_my_files"),
    path('my-files/', show_subs_files, name="show_subs_files"),
    path('upload/', Upload.as_view(), name='upload'),
    path('logout/', logout, name='logout')
]

drive/models.py
from django.contrib.auth.base_user import BaseUserManager

from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True)
    uploaded_size = models.IntegerField(default='0')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class File(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    file = models.FileField(upload_to='files/')
    size = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name="files", on_delete=models.CASCADE)
    subscribers = models.ManyToManyField(User, related_name='subs_files')

    def __str__(self):
        return self.name

drive/forms.py
from django import forms

from .models import File


class SignIn(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class UploadForm(forms.ModelForm):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = File
        fields = ('name', 'subscribers')

B_drive/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

drive/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout as lo
from django.views.generic import FormView

from .models import User, File
from .forms import SignIn, UploadForm


class Login(View):
    form = SignIn()
    ctx = {'form': form}

    def get(self, request):
        return render(request, 'drive/login.html', context=self.ctx)

    def post(self, request):
        form = SignIn(request.POST)
        if form.is_valid():
            print(6)
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            print(user)
            if user:
                login(request, user)
                print(8)
                return redirect(reverse('home'))
            else:
                print(7)
                self.ctx['message'] = "user doesn't exist"
                return render(request, 'drive/login.html', context=self.ctx)

        else:
            self.ctx['form'] = form
            return render(request, 'drive/login.html', context=self.ctx)


@method_decorator(login_required, name='dispatch')
class Upload(FormView):
    template_name = 'drive/upload.html'
    form_class = UploadForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('files')
        user = User.objects.get(email=request.user.email)
        if form.is_valid():
            size = 0
            for f in files:
                size += f.size
                name = form.cleaned_data.get('name', '')
                if name:
                    fi = File.objects.create(name=name, file=f, size=f.size, user=user)
                    for sub in form.cleaned_data.get('subscribers'):
                        if sub == user:
                            pass
                        else:
                            fi.subscribers.add(sub)
                            fi.save()
                else:
                    fi = File.objects.create(name=f.name, file=f, size=f.size, user=user)
                    for sub in form.cleaned_data.get('subscribers'):
                        if sub == user:
                            pass
                        else:
                            fi.subscribers.add(sub)
                            fi.save()
            user.uploaded_size += size
            user.save()
            return self.form_valid(form)

        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('drive:show_files')


@login_required
def show_my_files(request):
    if request.method == "GET":
        user = User.objects.get(email=request.user.email)
        user_files = user.files.all().values('name', 'file', 'date')
        ctx = {'files': user_files}
        return render(request, 'drive/files.html', context=ctx)\



@login_required
def show_subs_files(request):
    if request.method == "GET":
        user = User.objects.get(email=request.user.email)
        user_files = user.subs_files.all().values('name', 'file', 'date')
        ctx = {'files': user_files}
        return render(request, 'drive/files.html', context=ctx)


@login_required
def logout(request):
    lo(request)
    return redirect(reverse('home'))

drive/templates/drive/files.html
{% extends 'base.html' %}

{% block title %}
    My-Files
{% endblock title %}

{% block header %}
    <button type="button"><a href="{% url 'drive:logout' %}">Logout</a></button>
    <button type="button"><a href="{% url 'home' %}">Home</a></button>
{% endblock header %}

{% block content %}
    <h3>You have uploaded {{ request.user.uploaded_size}} bytes files</h3>
    <ul>
        {% for file in files %}
            <li><a href="{{ file.file }}" download>{{ file.name }}</a><span>-------</span>{{ file.size }} bytes</li>
            {% empty %}
            <p>No files to show</p>
        {% endfor %}
    </ul>

    <button type="button"><a href="{% url 'drive:upload' %}">Upload</a></button>

{% endblock content %}

drive/templates/drive/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock title %}

{% block header %}
    <button type="button"><a href="{% url 'home' %}">Home</a></button>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'drive:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button>
    </form>
{% endblock content %}

drive/templates/drive/upload.html
{% extends 'base.html' %}

{% block title %}
Upload-file
{% endblock title %}

{% block header %}
    <button type="button"><a href="{% url 'drive:logout' %}">Logout</a></button>
    <button type="button"><a href="{% url 'home' %}">Home</a></button>
{% endblock header %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} {% endblock title%}</title>
</head>
<body>
    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block header %}
    {% if user.is_authenticated %}
        <button type="button"><a href="{% url 'drive:logout' %}">Logout</a></button>
    {% else %}
        <button type="button"><a href="{% url 'drive:login' %}">login</a></button>
    {% endif %}

{% endblock header %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Hello {{ request.user.first_name }} {{ request.user.last_name }}</h1>
        <h2>Welcome to B_Drive</h2>
        <h3>You have uploaded {{ request.user.uploaded_size}} bytes files</h3>
        <button type="button"><a href="{% url 'drive:upload' %}">Upload</a></button>
        <button type="button"><a href="{% url 'drive:show_my_files' %}">my_files</a></button>
        <button type="button"><a href="{% url 'drive:show_subs_files' %}">subs_files</a></button>

    {% else %}
        <p>Welcome to B_Drive</p>
        <p>Please Login</p>
    {% endif %}
{% endblock content %}